export const json = {
  pages: [
    {
      elements: [
        {
          type: "checkbox",
          name: "medical_conditions",
          title: "Do you have any medical conditions? (We need to know your medical history to give you the best care.",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: [
            "High blood pressure",
            "Diabetes",
            "HIV",
            "Lupus",
            "Kidney problems",
            "Liver problems",
            "Thyroid problems",
            "Problems with the immune system",
            "Cancer (e.g. breast, colon, lung, leukemia, lymphoma, etc)",
            "Other",
            "No, I don’t have any medical conditions",
          ],
        },
        {
          name: "cancer_med_issue",
          type: "text",
          title: "What other medical conditions do you have?:",
          placeHolder: "...",
          isRequired: true,
          visibleIf: '{medical_conditions} contains "Other" ',
        },
        {
          type: "checkbox",
          name: "any_surgeries",
          title: "Have you ever had any surgeries? (Certain surgeries might impact how we approach your care.)",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: [
            "Orthopedic surgery",
            "Cosmetic surgery",
            "Hair transplant",
            "Cardiac surgery",
            "Liver of kidney surgery",
            "Other",
            "No, I have never had surgery",
          ],
        },
        {
          name: "cosmetic_surgey",
          type: "text",
          title: "What cosmetic surgeries have you had?:",
          placeHolder: "...",
          isRequired: true,
          visibleIf: '{any_surgeries} contains "Cosmetic surgery" ',
        },
        {
          type: "radiogroup",
          name: "take_any_medicines",
          title:
            "Do you currently take any medicines, herbals, and/or supplements? Please include any medicines you finished recently, including topical medicines. (This helps us ensure that our treatment recommendations don’t interfere with your existing medications.)",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: ["Yes", "No"],
        },
        {
          name: "yes_medicine",
          type: "text",
          title: "What medicines, herbals, and/or supplements do you use?:",
          placeHolder: "...",
          isRequired: true,
          visibleIf: '{take_any_medicines} contains "Yes" ',
        },
      ],
      name: "genHistory",
      navigationTitle: "Medical History",
    },
    {
      elements: [
        {
          type: "radiogroup",
          name: "Which of these describes how you feel about your skin?",
          title: "Which of these describes how you feel about your skin?",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: [
            "I’m doing well, just looking for ways to help keep my skin healthy",
            "I’m doing ok, I think my skin could be better and hope you can help",
            "Not great, I'm pretty bothered by the state of my skin at the moment",
            "I feel badly, my skin is really bothering me and causing me a lot of distress",
            "None",
          ],
        },
        {
          name: "How long have you been struggling with this issue?",
          type: "text",
          title: "How long have you been struggling with this issue?:",
          placeHolder: "...",
          isRequired: true,
        },
        {
          type: "checkbox",
          name: "Where have you been experiencing these problems?",
          title: "Where have you been experiencing these problems?",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: ["Forehead", "Cheeks", "Chin", "Around the mouth", "Neck", "Other", "No, I have never had surgery"],
        },
        {
          name: "Can you please describe which part of your body is affected?",
          type: "text",
          title: "Can you please describe which part of your body is affected?:",
          placeHolder: "...",
          isRequired: true,
          visibleIf: '{Where have you been experiencing these problems?} contains "Other" ',
        },
        {
          type: "radiogroup",
          name: "take_any_medicines",
          title:
            "Do you currently take any medicines, herbals, and/or supplements? Please include any medicines you finished recently, including topical medicines. (This helps us ensure that our treatment recommendations don’t interfere with your existing medications.)",
          isRequired: true,
          hasNone: false,
          colCount: 4,
          choices: ["Yes", "No"],
        },
        {
          name: "yes_medicine",
          type: "text",
          title: "What medicines, herbals, and/or supplements do you use?:",
          placeHolder: "...",
          isRequired: true,
          visibleIf: '{take_any_medicines} contains "Yes" ',
        },
      ],
      name: "medicalHistory",
      navigationTitle: "Acne",
      navigationDescription: "Visit Questions",
      questionTitleLocation: "top",
    },
  ],
  showProgressBar: "top",
  showQuestionNumbers: "off",
  progressBarType: "buttons",
  title: "Medicall Questionnaire",
};
