export const json = {
  pages: [
    {
      elements: [
        {
          type: "panel",
          name: "patientName",
          elements: [
            {
              type: "text",
              name: "patientLastName",
              title: "(Last)",
              isRequired: true,
            },
            {
              type: "text",
              name: "patienFirstName",
              startWithNewLine: false,
              title: "(First)",
              isRequired: true,
            },
            {
              type: "text",
              name: "patientMiddleName",
              startWithNewLine: false,
              title: "(M.I)",
            },
          ],
          questionTitleLocation: "top",
          title: "Patient Name",
        },
        {
          type: "panel",
          name: "panel2",
          elements: [
            {
              type: "text",
              name: "socialsecurity",
              title: "Social Security #:",
              isRequired: true,
              inputFormat: "999-99-9999",
            },
            {
              type: "text",
              inputType: "date",
              isRequired: true,
              name: "birthDate",
              startWithNewLine: false,
              title: "Date of birth:",
            },
            {
              type: "radiogroup",
              choices: [
                {
                  value: "male",
                  text: "Male",
                },
                {
                  value: "female",
                  text: "Female",
                },
              ],
              colCount: 0,
              isRequired: true,
              name: "sex",
              title: "Sex:",
            },
          ],
          questionTitleLocation: "top",
          title: "Social Security & Birth Date",
        },
        {
          type: "panel",
          name: "panel1",
          elements: [
            {
              type: "radiogroup",
              choices: [
                {
                  value: "patient",
                  text: "Patient",
                },
                {
                  value: "spouse",
                  text: "Spouse",
                },
              ],
              colCount: 0,
              hasOther: true,
              isRequired: true,
              name: "completedBy",
              otherText: "Other (specify)",
              title: "Who completed this form:",
            },
            {
              type: "text",
              name: "completedByOtherName",
              visibleIf: '{completedBy} != "patient"',
              startWithNewLine: false,
              title: "Name (if other than patient):",
              isRequired: true,
            },
          ],
          title: "Completed By",
          questionTitleLocation: "top",
        },
      ],
      name: "introduction",
      navigationTitle: "Introduction",
      navigationDescription: "General History",
    },
    {
      elements: [
        {
          type: "radiogroup",
          choices: [
            {
              value: "no",
              text: "No",
            },
            {
              value: "yes",
              text: "Yes",
            },
          ],
          colCount: 0,
          isRequired: true,
          name: "everhospitalized",
          title: "Have you ever been hospitalized?",
        },
        {
          type: "radiogroup",
          choices: [
            {
              value: "no",
              text: "No",
            },
            {
              value: "yes",
              text: "Yes",
            },
          ],
          colCount: 0,
          isRequired: true,
          name: "injuriesbrokenbones",
          title: "Have you had any serious injuries and/or broken bones?",
        },
        {
          type: "comment",
          isRequired: true,
          name: "injuriesbrokenbones_describe",
          startWithNewLine: false,
          title: "Describe",
          visible: false,
          visibleIf: '{injuriesbrokenbones} = "yes"',
        },
        {
          type: "radiogroup",
          choices: [
            {
              value: "unknown",
              text: "Unknown",
            },
            {
              value: "no",
              text: "No",
            },
            {
              value: "yes",
              text: "Yes",
            },
          ],
          colCount: 0,
          isRequired: true,
          name: "bloodtransfusion",
          title: "Have you ever received a blood transfusion?",
        },
        {
          type: "text",
          name: "bloodtransfusion_years",
          visible: false,
          visibleIf: '{bloodtransfusion}="yes"',
          startWithNewLine: false,
          title: "Approximate year(s)",
        },
        {
          type: "radiogroup",
          choices: [
            {
              value: "no",
              text: "No",
            },
            {
              value: "yes",
              text: "Yes",
            },
          ],
          colCount: 0,
          isRequired: true,
          name: "ousideUSACanada",
          title: "Have you ever traveled or lived outside the United States or Canada?",
        },
        {
          type: "comment",
          isRequired: true,
          name: "ousideUSACanada_describe",
          startWithNewLine: false,
          title: "Describe",
          visible: false,
          visibleIf: '{ousideUSACanada} = "yes"',
        },
        {
          type: "matrixdropdown",
          name: "immunizations",
          title:
            "Have you received the following IMMUNIZATIONS?  If yes, indicate the approximate year it was last given:",
          columns: [
            {
              name: "answer",
              title: "Please select",
              choices: [
                {
                  value: "unknown",
                  text: "Unknown",
                },
                {
                  value: "no",
                  text: "No",
                },
                {
                  value: "yes",
                  text: "Yes",
                },
              ],
              cellType: "radiogroup",
              isRequired: true,
            },
            {
              name: "year",
              title: "Year",
              cellType: "text",
              isRequired: true,
              visibleIf: '{row.answer} = "yes"',
            },
          ],
          choices: [1, 2, 3, 4, 5],
          rows: [
            "Pneumococcal (for pneumonia)",
            "Hepatitis A",
            "Hepatitis B",
            "Tetanus/Diphtheria within last 10 years",
            "Influenza (flu)",
            "Measles",
            "Mumps",
            "Rubella",
            "Polio",
          ],
        },
        {
          type: "matrixdynamic",
          name: "problems1",
          title: "Have you ever had any of the following?",
          columns: [
            {
              name: "problem",
              title: "Problem",
              choices: [
                "Abnormal chest x-ray",
                "Anesthesia complications",
                "Anxiety, depression or mental illness",
                "Blood problems (abnormal bleeding, anemia, high or low white count)",
                "Diabetes",
                "Growth removed from the colon or rectum (polyp or tumor)",
                "High blood pressure",
                "High cholesterol or triglycerides",
                "Sexually transmitted disease",
                "Stroke or TIA",
                "Treatment for alcohol and/or drug abuse",
                "Tuberculosis or positive tuberculin skin test",
                "Cosmetic or plastic surgery",
              ],
            },
            {
              name: "answer",
              title: "Please answer",
              choices: [
                {
                  value: "no",
                  text: "No",
                },
                {
                  value: "yes",
                  text: "Yes",
                },
              ],
              cellType: "radiogroup",
              isRequired: true,
            },
            {
              name: "description",
              title: "Describe the problem",
              cellType: "comment",
              isRequired: true,
              visibleIf: '{row.answer} = "yes"',
            },
          ],
          choices: [1, 2, 3, 4, 5],
          rowCount: 1,
        },
        {
          type: "matrixdynamic",
          name: "problems2",
          title: "Indicate whether you have ever had a medical problem and/or surgery related to each of the following",
          columns: [
            {
              name: "problem",
              title: "Problem",
              choices: [
                "Eyes (cataracts, glaucoma)",
                "Ears, nose, sinuses, or tonsils",
                "Thyroid or parathyroid glands",
                "Heart valves or abnormal heart rhythm",
                "Coronary (heart) arteries (angina)",
                "Arteries (aorta, arteries to head, arms, legs) ",
                "Veins or blood clots in the veins",
                "Lungs",
                "Esophagus or stomach (ulcer)",
                "Bowel (small & large intestine)",
                "Appendix",
                "Liver or gallbladder (including hepatitis)",
                "Hernia",
                "Kidneys or bladder",
                "Bones, joints or muscles",
                "Back, neck or spine",
                "Brain",
                "Skin",
                "Breasts",
                "Females: uterus, tubes, ovaries",
                "Males: prostate, penis, testes, vasectomy",
                "Other: Describe",
              ],
              cellType: "dropdown",
              isRequired: true,
              choicesOrder: "asc",
            },
            {
              name: "type",
              title: "Type",
              choices: [
                {
                  value: "medical",
                  text: "Medical Problem",
                },
                {
                  value: "surgery",
                  text: "Surgery",
                },
              ],
              cellType: "checkbox",
              isRequired: true,
            },
            {
              name: "year",
              title: "Year(s) of Surgery",
              cellType: "text",
              isRequired: true,
              visibleIf: '{row.type} contains "surgery"',
            },
            {
              name: "describe",
              title: "Describe",
              cellType: "comment",
              isRequired: true,
            },
          ],
          choices: [1, 2, 3, 4, 5],
          rowCount: 1,
          addRowText: "Add Problem",
        },
      ],
      name: "medicalHistory",
      navigationTitle: "Acne",
      navigationDescription: "Visit Questions",
      questionTitleLocation: "left",
    },
  ],
  showProgressBar: "top",
  showQuestionNumbers: "off",
  progressBarType: "buttons",
  title: "Medicall Questionnaire",
};
