const CheckoutActionTypes = {
  FETCH_STRIPE_CLIENT_SECRET_START: 'FETCH_STRIPE_CLIENT_SECRET_START',
  FETCH_STRIPE_CLIENT_SECRET_SUCCESS: 'FETCH_STRIPE_CLIENT_SECRET_SUCCESS',
  FETCH_STRIPE_CLIENT_SECRET_FAILURE: 'FETCH_STRIPE_CLIENT_SECRET_FAILURE',
};

export default CheckoutActionTypes;
