const CheckoutActionTypes = {
  FETCH_STRIPE_URL_START: 'FETCH_STRIPE_URL_START',
  FETCH_STRIPE_URL_SUCCESS: 'FETCH_STRIPE_URL_SUCCESS',
  FETCH_STRIPE_URL_FAILURE: 'FETCH_STRIPE_URL_FAILURE',
};

export default CheckoutActionTypes;
