const DoctorsActionTypes = {
  //SINGLE DOCTOR
  FETCH_DOCTOR_START: 'FETCH_DOCTOR_START',
  FETCH_DOCTOR_SUCCESS: 'FETCH_DOCTOR_SUCCESS',
  FETCH_DOCTOR_FAILURE: 'FETCH_DOCTOR_FAILURE',
  //DOCTORS LIST
  FETCH_DOCTORS_LIST_START: 'FETCH_DOCTORS_LIST_START',
  FETCH_DOCTORS_LIST_SUCCESS: 'FETCH_DOCTORS_LIST_SUCCESS',
  FETCH_DOCTORS_LIST_FAILURE: 'FETCH_DOCTORS_LIST_FAILURE',
};

export default DoctorsActionTypes;
